<a href="https://colab.research.google.com/github/larimscorrea/jd-introduction-python/blob/main/second_step.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **NUMPY ARRAYS**

Array é uma estrutura de dados que armazena uma coleção de elementos e que cada um dos elementos pode ser identificado por, pelo menos, um índice ou uma chave.

In [1]:
import numpy as np

In [2]:
lista = list(range(10))

In [3]:
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(lista)

list

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10,3)

array([1, 4, 7])

**LISTA CONVERTIDA EM ARRAY**

In [11]:
a = np.array(lista)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
type(a)

numpy.ndarray

**LISTA COM VÁRIOS TIPOS DE VARIÁVEIS**

In [13]:
misturados = [2.3, 9, 'nome', False]

**ESTRUTURA DE REPETIÇÃO**

In [14]:
for el in misturados:
    print(type(el))

<class 'float'>
<class 'int'>
<class 'str'>
<class 'bool'>


In [15]:
misturados_array = np.array(misturados)
type(misturados_array)

numpy.ndarray

**ARRAY CONVERTIDO EM STRING**

In [16]:
for el in misturados_array:
    print(type(el))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [17]:
nums = [1,2,3,4,5.0]
np.array(nums)

array([1., 2., 3., 4., 5.])