<a href="https://colab.research.google.com/github/larimscorrea/jd-introduction-python/blob/main/third_step.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **NUMPY ARRAYS**

Array é uma estrutura de dados que armazena uma coleção de elementos e que cada um dos elementos pode ser identificado por, pelo menos, um índice ou uma chave.

In [ ]:
import numpy as np

In [ ]:
lista = list(range(10))

In [ ]:
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(lista)

list

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,3)

array([1, 4, 7])

**LISTA CONVERTIDA EM ARRAY**

In [ ]:
a = np.array(lista)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(a)

numpy.ndarray

**LISTA COM VÁRIOS TIPOS DE VARIÁVEIS**

In [ ]:
misturados = [2.3, 9, 'nome', False]

**ESTRUTURA DE REPETIÇÃO**

In [ ]:
for el in misturados:
    print(type(el))

<class 'float'>
<class 'int'>
<class 'str'>
<class 'bool'>


In [ ]:
misturados_array = np.array(misturados)
type(misturados_array)

numpy.ndarray

**ARRAY CONVERTIDO EM STRING**

In [ ]:
for el in misturados_array:
    print(type(el))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
nums = [1,2,3,4,5.0]
np.array(nums)

array([1., 2., 3., 4., 5.])

## **OPERAÇÕES INTELIGENTES**

**CRIANDO UMA LISTA**

In [ ]:
lista = [1,2,3,4,5]

**DEFININDO COMO UM ARRAY**

In [ ]:
array = np.array(lista)

In [ ]:
array+20


array([21, 22, 23, 24, 25])

In [ ]:
lista+10

TypeError: ignored

**LISTA VAZIA**

In [ ]:
lista20 = []

**ESTRUTURA DE REPETIÇÃO**

In [ ]:
lista20 = 1, 3, 5, 7
for n in lista:
    lista20.append(n+20)

AttributeError: ignored

**RAIZ QUADRADA**

# **NUMPY ARRAYS: INDEXANDO E CORTANDO 'SICLING'**

In [ ]:
array = np.arange(1,11)